#!/bin/bash
clear
echo -e "=========================\n"
echo "Welcome To Terminal Radio"
echo -e "\n=========================\n\n"
echo -e "__________________________\n"
echo -e "MENU FOR RADIO STATIONS"
echo -e "__________________________"
echo "1)BBC World Service News Stream"
echo "2)BBC World Service UK Stream"
echo "3)BBC Asian Network"
echo "4)BBC Radio 3"
echo "5)BBC Radio 4"
echo "6)BBC Radio 5 live"
echo "7)BBC Radio 5 live sportball extra"
echo "8)BBC Radio 6 Music"
echo "9)BBC Radio 2"
echo "10)BBC Radio 1"
echo "11)Kantipur Radio"
echo  "12)BBC 1xtra"
echo -e "13)Radio Nepal"

read -p "What would you like to hear: " choice
station=$(sed "${choice}q;d" stations)

case "$choice" in
	1)
		clear
		echo "BBC World Service News Stream"
		mplayer $station 
		;;
	2)
		clear
		echo "BBC World Service UK Stream"
		mplayer $station 
		;;
	3)
		clear
		echo "BBC Asian Network"
		mplayer $station
		;;
	4)
		clear
		echo "BBC Radio 3"
		mplayer $station
		;;
	5)
		clear
		echo "BBC Radio 4"
		mplayer $station
		;;
	6)
		clear
		echo "BBC Radio 5 live"
		mplayer $station
		;;
	7)
		clear
		echo "BBC Radio 5 live sportball extra"
		mplayer $station
		;;
	8)
		clear
		echo "BBC Radio 6 Music"
		mplayer $station
		;;
	9)
		clear
		echo "BBC Radio 2"
		mplayer $station
		;;
	10)
		clear
		echo "BBC Radio 1"
		mplayer $station
		;;
	11)
		clear
		echo "Kantipur Radio"
		mplayer $station
		;;
	12)
		clear
		echo "BBC 1xtra"
		mplayer $station
		;;
	13)	
		clear
		echo "Radio nepal"
		mplayer $station
		;;
	*)
		echo "Invalid choice...Quitting...."
		exit 0
		;;
esac
