#!/bin/bash
clear
echo -e "=========================\n"
echo "Welcome To Terminal Radio"
echo -e "\n=========================\n\n"
echo -e "__________________________\n"
echo -e "MENU FOR RADIO STATIONS"
echo -e "__________________________"
echo "1)BBC World Service News Stream"
echo "2)BBC World Service UK Stream"
echo "3)BBC Asian Network"
echo "4)BBC Radio 3"
echo "5)BBC Radio 4"
echo "6)BBC Radio 5 live"
echo "7)BBC Radio 5 live sportball extra"
echo "8)BBC Radio 6 Music"
echo "9)BBC Radio 2"
echo "10)BBC Radio 1"
echo "11)Kantipur Radio"
echo  "12)BBC 1xtra"
echo -e "13)Radio Nepal"

read -p "What would you like to hear today: " choice
station=$(sed "${choice}q;d" stations)

mplayer $station
